image: registry.gitlab.com/wldhx/gitlab-ci-react-native-android:master

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/
  - .gradle/
  
stages:
  - test
  - build

before_script:
  - apt-get install -y locales
  - locale-gen en_US.UTF-8
  - export LANG='en_US.UTF-8' 
  - export LANGUAGE='en_US:en' 
  - export LC_ALL='en_US.UTF-8'
  - echo fs.inotify.max_user_instances=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - echo fs.inotify.max_queued_events=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./android/gradlew
  - yarn install

test:
  stage: test
  script:
    - yarn lint
    - yarn test

build:
  stage: build
  script:
    - (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
    - cd android/
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release.apk
